# Generated by Django 4.1.7 on 2023-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_of_sportfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
